### ISSUE TITLE
Syntax highlighting not displaying on Windows 10

### ISSUE THREAD

**Issue by pflugs30** [kumarharsh/graphql-for-vscode#113]
OS: Windows 10 Home Edition version 1083
VS code: 1.27.2
GraphQL for VSCode: 1.12.1

I've installed GraphQL for VSCode on two of my dev machines.  On my desktop running Windows 7, the extension installed and needed no configuration in order to display syntax highlighting and the other features like go-to-definition.  On my laptop running Windows 10 Home edition, the extension installed but does not display syntax highlighting for *.graphql files.

I've tried:
- performing the steps in the extension's "Setting it Up" section, including installing **Watchman** and adding it to the PATH variable
- installing other GraphQL extensions (including GraphQL from Prisma)
- [tested GraphQL language features](https://github.com/prisma/vscode-graphql#a-testinglogging-graphql-language-features)

I'm confused as to why highlighting isn't working for any of the extensions I've tried.  I'm looking for suggestions on things I can try.  Has anyone else had this problem?

**Comment by kumarharsh** [comment]
Syntax highlighting doesn't have anything to do with watchman. Most probably it's happening because you'd have installed a different JS syntax highlighting plugin which might be old... Please install this extension: https://marketplace.visualstudio.com/items?itemName=mgmcdermott.vscode-language-babel

And ensure that the watchman binary is in your path when you start vscode.

**Comment by pflugs30** [comment]
Hi @kumarharsh, thanks for the reply.  I confirmed Watchman was in the PATH when VSCode was started (ran `watchman --version` in a command prompt).  I also installed the extension you recommended, but it didn't make a difference in the highlighting.  Also, through the User Settings, I added `"graphqlForVSCode.debug": true`, but I am not seeing any logs.

To clarify, I'm seeing _some_ highlighting: namely, comments and keywords are highlighted (see screenshot below).  However, I'm not getting the full effects of the extension.  Could there be something wrong with a dependency (for example, not being able to find `@playlyfe/gql`)?
![image](https://user-images.githubusercontent.com/4409272/45585783-f7bdd180-b8af-11e8-849c-f772884bd926.png)

**Comment by pflugs30** [comment]
Update:
- I also tried adding the `@playlyfe/gql` package manually to my project by running `yarn add @playlyfe/gql --dev`.
- I added a setting to the Workspace settings: `"graphqlForVSCode.nodePath": "../data-api/node_modules"` (since I have three folders in my workspace).
- I added a file named `.gqlconfig` containing:
```
{
  schema: {
    files: '**/*.graphql'
  }
}
```

After restarting VSCode, I saw a new log for **GraphQL for VSCode** in the **Output** window, and it contained the following:

```
[Info  - 7:44:21 AM] NODE_PATH value is: c:\Users\mpflu\Documents\Code\ALS\data-api\node_modules
[Info  - 7:44:24 AM] Module '@playlyfe/gql' loaded from: c:\Users\mpflu\Documents\Code\ALS\data-api\node_modules\@playlyfe\gql\lib\index.js
```

But I still see no change in the syntax highlighting of my GraphQL files (all of which are named '*.graphql'.

**Comment by kumarharsh** [comment]
@pflugs30 the syntax highlighting part should work **without any setup**. You just install this plugin and it should work. Since it's not working, can you try disabling all plugins and just enable this plugin and Language Babel and then restart VSCode, and then see if highlighting works? If it does, then enable other plugins one by one. It's possible there is some conflict with another plugin.

**Comment by pflugs30** [comment]
Hi @kumarharsh,

I did as you suggested and disabled all extensions except Babel Javascript and GraphQL for VSCode.  Sadly, it didn't change anything.  I'm still seeing only comments and type/enum keywords highlighted.  I'm not sure what else I try... :-)

**Comment by kumarharsh** [comment]
Can you change the extension to .gql and see if it works?

**Comment by pflugs30** [comment]
no difference.  Note: when I tested, I did not have a `.gqlconfig` file in the workspace.

**Comment by kumarharsh** [comment]
@pflugs30 sorry for getting back to you late, but I think I figured out what's wrong. Are you using the `Dark` theme of VSCode? This is the only possible explanation I can think of which would cause this issue. This is because the Dark theme is very very basic and doesn't have support for a lot of token classes. Can you use the Dark+ theme and confirm that syntax highlighting is working?

**Comment by pflugs30** [comment]
That was it!!  Thank you so much.  I never would have thought of that solution.  As soon as I changed it from `Dark (Visual Studio)` to `Dark+ (default dark)`, all the highlighting displayed correctly.  Very much appreciated!

**Comment by garysdevil** [comment]
Cool. I would be crazy for this question.
