### ISSUE TITLE
custom colors for directives

### ISSUE THREAD

**Issue by zwhitchcox** [kumarharsh/graphql-for-vscode#137]
Hi, I'm using your graphql syntax highlighter, and I'm wondering how hard it would be to modify it where you can color code your directives.

So, I have two directives that I use repetitively, and it would be easier to quickly distinguish the two if they were color coded.

So, for instance something like

```graphql
type User {
    name: String!
      @c(role: USER)
      @validation(min: 3, max: 4)
    email: String!
      @validation(preset: 'email')
      @r(roles: [OWNER, USER])
    
}
```
So, you can see how this can get a little visually cluttered. Anyway, I'm just wondering how hard it would be to do/where to start. I've downloaded the code, and it looks like I would edit the `graphql.json` file, but this is all totally new to me, so just wondering if you could point me in the right direction.

Anyway, thanks in advance!

**Comment by kumarharsh** [comment]
I don't think VSCode provides an API to specify custom colours to different parts of the same type. Can you give me an example where you've seen such a thing in action, so that we can think of some solution to this.

Do correct me if I'm wrong, but I think what you want is to designate some specific directives (like `@validation`, but there can be others too) in a muted colour, and the rest of the directives normally. If that is the case, maybe we can build a list of common directives we can look into supporting as muted versions of the directives style. Although in practice, building such a list can be cumbersome and prone to debate. Let me know your thoughts.

**Comment by zwhitchcox** [comment]
Hey Kumar!

Thanks for getting back to me...I actually did figure this out though, and I forgot I had opened this issue.

I was able to solve my use case somewhat simply using [decorations](https://github.com/zwhitchcox/graphql-authorization-and-validation-directives-highlighting/blob/master/src/extension.js), and I open sourced the extension as you can see.

I tried going the syntax highlighting route though, and you're right, I don't think that was the best way to do it, because even after you get the syntax highlighter working, then you have to get the theme to recognize it, and everyone has different themes.

Maybe you could do it with certain designated colors, but I think my use case is so project-specific, it wouldn't really make sense to put it in the syntax highlighter.
