### ISSUE TITLE
Syntax highlighting fails inside backticks

### ISSUE THREAD

**Issue by ozguruysal** [kumarharsh/graphql-for-vscode#55]
If I have a space between the backtick and `default` keyword syntax highligting fails

![graphql-4-vscode-11](https://user-images.githubusercontent.com/53624/33230435-5f073528-d1f4-11e7-8a6c-c78cbe30db33.png)

If I remove the space all works nicely

![graphql-4-vscode-2](https://user-images.githubusercontent.com/53624/33230432-4a0afb14-d1f4-11e7-9456-ede99104fb59.png)

I can easily workaround this issue by removing the space, however I'm using Prettier and it's enforcing a space in between the backtick and `default`.

**Comment by kumarharsh** [comment]
This extension isn't designed to highlight either of the cases you've presented, because it looks for the `Relay.QL` or `gql` tag before the template string to inject the syntax grammar. Might some other plugin be causing the highlighting?

**Comment by kumarharsh** [comment]
Unfortunately, it's not easy to do this. See [this issue](https://github.com/kumarharsh/graphql-for-vscode/issues/52) for details. And this comment addresses why it's not a viable solution: https://github.com/kumarharsh/graphql-for-vscode/issues/52#issuecomment-341680577

You can use the workaround [given here](https://github.com/kumarharsh/graphql-for-vscode/issues/52#issuecomment-341804118) to get the syntax highlighting, autocompletion and linting!

**Comment by ozguruysal** [comment]
I'm not using `gql` tag and if you write the schema this way it's always guaranteed that it'll start wih `export default`. So the issue is different than mine. But thanks anyways.

**Comment by kumarharsh** [comment]
The core of the issue is the same:

The editor doesn't know – and there's no easy way to inform the editor (that I know of) – that **all** text starting with `export default` would be only gql. So, either the plugin will have to treal **all** exported text as graphql text, or not highlight anything. I've chosen the safer option in this plugin to avoid confusion. 

The tagged-template literal approach is an explicit declaration that what follows is definitely graphql. You can still get autocomplete, and other language-service features by setting up your gqlconfig with the syntax you'd like to match. If you'd like to have syntax highlighting too, you can try the approach I recommended in the workaround.

The proper solution to this would ideally be a way to tell vscode a set of user-specified matchers for grammar injection. Though, I don't know if that's possible, or if implementing it would be feasible for them. @mjbvz?
