### ISSUE TITLE
Support custom directives

### ISSUE THREAD

**Issue by kabytaa** [kumarharsh/graphql-for-vscode#66]
Hi,

I am not sure if there is a support for custom directives or i'm doing something wrong.
I have this code:

```graphql
directive @myDirective on FIELD

type Query{
    getData:String! @myDirective
}
```
And i get this error:
> [graphql] Directive "noLogin" may not be used on FIELD_DEFINITION. (KnownDirectives)

How i can fix it?

BTW: Awesome extension.

Thanks

**Comment by Mayank1791989** [comment]
Please share your .gqlconfig file.

**Comment by kabytaa** [comment]
my .gqlconfig file
```javascript
// .gqlconfig (with query) 
{
  schema: {
    files: 'src/**/*.gql',
  },
  query: {
    files: [
      // query gql files 
      {
        match: 'src/**/*.gql',
        parser: 'QueryParser',
      },
      // [Embedded queries] relay files 
      {
        match: { include: 'src/**/*.js', ignore: '**/tests/**/*.js' },
        parser: [ 'EmbeddedQueryParser', { startTag: 'Relay\\.QL`', endTag: '`' } ],
        isRelay: true,
      },
      // [Embedded queries] gql tag files 
      {
        match: { include: 'src/**/*.js', ignore: '**/tests/**/*.js' },
        parser: [ 'EmbeddedQueryParser', { startTag: 'gql`', endTag: '`' } ],
      },
      // [Embedded queries] some other tags  
      {
        match: 'src/**/*.xyz',
        parser: [ 'EmbeddedQueryParser', { startTag: '"""', endTag: '"""' } ],
      },
      // [Embedded queries] some other tags and modify validation rules 
      {
        match: 'src/**/*.xyz',
        parser: [ 'EmbeddedQueryParser', { startTag: '"""', endTag: '"""' } ],
        validate: {
          extends: 'gql-rules-query',
          rules: {
            LoneAnonymousOperation: 'off',
            NoUnusedVariables: 'warn',
          },
        }
      },
    ]
  }
}

```

I tried to change the file for following json and it stoped to show me the error. 

```javascript
// .gqlconfig (with query) 
{
  schema: {
    files: 'src/**/*.gql',
  }
}

```

what is the problem with the previous file?

Thanks

**Comment by kumarharsh** [comment]
The previous file is an example file - meant to show how to configure your project.

The errors have stopped because the linting has stopped. You need to specify the `query` config depending on the files you want linting, autocomplete, etc to be activated for.

For example, to enable linting, etc for *.gql and *.js files, write this:

```
// .gqlconfig (with query) 
{
  schema: {
    files: 'src/**/*.gql',
  },
  query: {
    files: [
      // query gql files 
      {
        match: 'src/**/*.gql',
        parser: 'QueryParser',
      },
      // [Embedded queries] relay files 
      {
        match: { include: 'src/**/*.js', ignore: '**/tests/**/*.js' },
        parser: [ 'EmbeddedQueryParser', { startTag: 'Relay\\.QL`', endTag: '`' } ],
        isRelay: true,
      },
    ]
  }
}
```

**Comment by Mayank1791989** [comment]
> what is the problem with the previous file?
```js 
{
  schema: {
    files: 'src/**/*.gql',
  }
}
```
The above .gqlconfig file is fine if you are using plugin for schema files only but if you want to support queries (using apollo, relay or other any other client) than you need to add 'query' in .gqlconfig.

> I tried to change the file for following json and it stoped to show me the error.

It stopped showing error as currently in schema directive validation is not done (I have created an issue
see here https://github.com/Mayank1791989/gql/issues/93). 

But with other config its showing error because you put schema files in query also and the error is coming from query validation rules. Note In graphql schema and query files are different and you should not put schema files in query files config they should be separate.

```diff
{
   schema: {
      files: 'src/**/*.gql',
  },
  query: {
    files: [{
-    match: 'src/**/*.gql'
+    match: 'src/path_to_query_files_not_schema_files',
    }]
  }
}
```
> [graphql] Directive "noLogin" may not be used on FIELD_DEFINITION. (KnownDirectives)
```graphql
directive @myDirective on FIELD

type Query{
    getData:String! @myDirective
}
```
In above code the **@myDirective** type definition is wrong. If you want to use directive on type definition fields than you should define your directive as below.
```diff
- directive @myDirective on FIELD
+ directive @myDirective on FIELD_DEFINITION
```

**Comment by kumarharsh** [comment]
I believe this has been resolved @kabytaa?

**Comment by kabytaa** [comment]
Yes, it solved, Thanks to @Mayank1791989.
