### ISSUE TITLE
Validation does not work

### ISSUE THREAD

**Issue by tomitrescak** [kumarharsh/graphql-for-vscode#94]
Hi, thanks for the wonderful extension. I followed your instructions and type navigation works and I have no errors in the console. Yet, I have no error checking and validation in my .gql files. Any idea how to debug this? I tries searching other issues to no avail.

**Comment by tomitrescak** [comment]
Nevermind .. it work on save, not live edit. Sorry for chaos.

**Comment by kumarharsh** [comment]
@tomitrescak thanks for using the plugin ❤

The extension only validates the files as they are **on disk**. The in-memory version of the files (which are unsaved) are not validated. This is because this extension relies on the `gql` library which uses `watchman` as the watching service. And by the very nature of it, watchman only works with files on-disk.

See https://github.com/Mayank1791989/gql/blob/master/src/schema/SchemaBuilder/GQLSchemaBuilder.js#L48

**Comment by tomitrescak** [comment]
Thanks for getting back to me. No worries, it as an AMAZING effort and works very well. The live edit would be a bonus, but I know that with integrating 3rd party sw it's always finicky.
